### ISSUE TITLE
iva version check of external programs fails

### ISSUE THREAD

**Issue by sdwfrost** [sanger-pathogens/iva#78]
IVA using Python3.6 (Homebrew) on OSX El Capitan gives me the following error. As a workaround, I've just commented out lines 102 and 103 of `external_progs.py`.

```
Traceback (most recent call last):
  File "/usr/local/bin/iva", line 129, in <module>
    iva.external_progs.get_all_versions(iva.external_progs.assembly_progs)
  File "/usr/local/lib/python3.6/site-packages/iva/external_progs.py", line 102, in get_all_versions
    if prog in minimum_versions and LooseVersion(version) < LooseVersion(minimum_versions[prog]):
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by andrewjpage** [comment]
My guess is that one of the dependancies is printing out a letter instead of a number in the version string. We would need to update the regular expression to catch that case.  Would it be possible for you send us the output of the following software?

blastn -version
makeblastdb -version
kmc
kmc_dump
kraken --version
kraken-build --version
nucmer --version
R --version
smalt version
samtools

**Comment by sdwfrost** [comment]
Here you go!

```sh
$ blastn -version
blastn: 2.6.0+
 Package: blast 2.6.0, build Aug 23 2017 22:18:50
 
$ makeblastdb -version
makeblastdb: 2.6.0+
 Package: blast 2.6.0, build Aug 23 2017 22:18:50
 
$ kmc
K-Mer Counter (KMC) ver. 3.0.0 (2017-01-28)

$ kmc_dump
KMC dump ver. 3.0.0 (2017-01-28)

$ nucmer --version
nucmer 
NUCmer (NUCleotide MUMmer) version 3.1

$ R --version
R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

$ smalt version

              SMALT - Sequence Mapping and Alignment Tool
Version: 0.7.6
Date:    21-03-2014
```

**Comment by andrewjpage** [comment]
Thanks for the version information. I've updated the external version checking software and added in a load of tests to check for a variety of different outputs. Hopefully version 1.0.9 fixes your issue.
